apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: riteshdockerhub036/k8s-fleetman-api-gateway:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

